### ISSUE TITLE
Sugestão da inclusão da variável RACA_COR na estrutura mínima

### ISSUE THREAD

**Issue by laiovictor** [fulvionedel/csapAIH#10]
Olá, acho que seria bastante útil para muitas análises se a variável RACA_COR estivesse incluída na estrutura mínima para uso nas funções do pacote. Tenho tentado usar um for loop para a extração da raça/cor e cbind() para montagem de uma tabela conjunta com os dados da função csapAIH(). O problema é não ter a funcionalidade das funções desenhaCSAP() e descreveCSAP(), além do tempo enorme para rodar o for loop de mais de 500.000 observações.  
De modo geral, parabéns pelo excelente e valiosíssimo trabalho! Será de grande utilidade para o meu projeto de mestrado!

**Comment by fulvionedel** [comment]
Olá @laiovictor, obrigado pela sugestão.
Tenho pensado em incluir como argumento da função csapAIH() um vetor pra seleção de variáveis. Mas pode ser mais rápido só acrescentar essa variável. Esse problema deveria ser contornado usando a função apenas sobre a variável com o CID do diagnóstico de internação como um vetor, não fosse o bug que relataste em outra mensagem.
Vou olhar essas coisas.

**Comment by fulvionedel** [comment]
Olá @laiovictor 
Agora que (espero) foi corrigido o erro que notaste, há uma solução para este. Podes gerar o data.frame com a função csapAIH e então unir ("merge", com as funções básicas, ou "inner_join" se usar o pacote dplyr) a ele o data.frame da AIH, apenas com as variáveis de interesse. Isso não é difícil, porque o banco com a classificação das CSAP mantém o nº da AIH.
Vê esse exemplo, usando e excelente pacote 'microdatasus', do Raphael Saldanha:
`
aih <- microdatasus::fetch_datasus(2021, 1, 2021, 1, uf = "AC", information_system = "SIH-RD")

csapAIH(aih) |>
  merge(aih[, c('N_AIH', 'RACA_COR')], by.x = "n.aih", by.y = "N_AIH") |>
  names()
`

Pra mais variáveis, dá pra criar um vetor com o nome das variáveis pra usar no merge:
Incluí um exemplo na ajuda da função.

`
aih <- microdatasus::fetch_datasus(2021, 1, 2021, 1, uf = "AC", information_system = "SIH-RD")

vars <- c('N_AIH', 'RACA_COR', ...)
csapAIH(aih) |>
  merge(aih[, vars], by.x = "n.aih", by.y = "N_AIH") |>
  names()
`
Incluí um exemplo na ajuda da função.

Espero que solucione o problema.

**Comment by fulvionedel** [comment]
Oi @laiovictor, novamente :)
Voltei a ler tua mensagem inicial e me dei conta de que a solução posta acima atrasa ainda mais o loop.
Nesse caso lista as variáveis de interesse da AIH no argumento 'vars' do pacote microdatasus. Se já tens os dados no computador, imagino que já tenhas apenas as variáveis de interesse e então os novos exemplos na ajuda da função 'csapAIH' devem ajudar.

**Comment by laiovictor** [comment]
Oi @fulvionedel 
Gostei bastante das mudanças! Testei usando o merge ou selecionando as variáveis a partir do` fetch_datasus()`. Acabei preferindo de fato a segunda opção, por ser mais rápida. No entanto, precisei excluir as AIHs de longa permanência antes de usar a função `csapAIH()` porque incluindo a variável `RACA_COR`, o banco deixa de ter a estrutura mínima. Também senti falta da facilidade da divisão em faixas etárias que a função traz quando `sihsus = T`.

**Comment by fulvionedel** [comment]
Oi @laiovictor 
Que bom, fico feliz. Sobre a computação das faixas etárias, o que faltou foi clareza quando comentei na mensagem que a idade pode ser calculada pela função 'idadeSUS', desculpa. Dá uma olhada na ajuda da função (`?idadeSUS()`), é ela quem computa a idade e a partir daí categoriza nas faixas etárias usadas nas tabulações do DATASUS. O resultado é um data.frame com três variáveis: "idade" (numérica), "fxetar.det" (fator) e "fxetar5" (fator), como ao usar os argumentos padrão de `csapAIH()`.

Assim, uma vez criado o banco, podes simplesmente acrescentar essas colunas com um `cbind()`, por exemplo:
```
library(microdatasus)
aih <- fetch_datasus(2021, 1, 2021, 1, uf = "AC", information_system = "SIH-RD")

library(csapAIH)
nova.aih <- cbind(aih, idadeSUS(aih))
```

Acho que essa é normalmente a forma mais fácil. Mas se há outras linhas de código pro manejo do banco já na sua leitura, ou se só interessa uma das variáveis -- muitas vezes só importa a "fxetar5" --, pode ser feito numa linha só com ajuda do pacote dplyr:
```
library(dplyr)
aih <- aih %>% 
  mutate(idade = idadeSUS(.)$idade,           # ou idadeSUS(.)[[1]]
         fxetar.det = idadeSUS(.)$fxetar.det, # ou idadeSUS(.)[[2]]
         fxetar5 = idadeSUS(.)$fxetar5        # ou idadeSUS(.)[[3]]
         )
```

As AIH de longa permanência (AIH tipo '5') são poucas e sua exclusão não é importante. A informação está na variável "IDENT"
e os registros podem ser excluídos com:
```
aih <- filter(aih, IDENT != "5")
```

Colocando tudo numa linha:
```
aih <- fetch_datasus(2021, 1, 2021, 1, uf = "AC", information_system = "SIH-RD") %>% 
  filter(IDENT != "5") %>% 
  mutate(idade = idadeSUS(.)$idade,           
         fxetar.det = idadeSUS(.)$fxetar.det, 
         fxetar5 = idadeSUS(.)$fxetar5)       
```

Espero ter ficado mais claro :) Vou fechar o "issue". Se achares pertinente, podes reabrir.
