### ISSUE TITLE
Cálculo para municípios

### ISSUE THREAD

**Issue by igortadeu** [fulvionedel/csapAIH#11]
Olá! Estou utilizando seu pacote para um trabalho experimental e está sendo muito útil. No entanto, quando executo o algoritmo para municípios com poucas observações, ele pode retornar 3 erros.

1º erro - Quando o data frame não possui observações suficientes contendo todas as faixas etárias, **idadeSUS()** em **csapAIH()** retorna um erro.

_Error in cut.default(idade, include.lowest = TRUE, right = FALSE, breaks = c(0:19,   : 
      'breaks' are not unique_

O erro acontece em:
```
idade <- csapAIH::idadeSUS(x)["idade"]
```

2º erro - Quando o ifelse() em **listaBRMS()** retorna somente 1 ou 2.

_Error: factor()':
_! invalid 'labels'; length 2 should be 1 or 1_

O erro acontece em:
```
csap <- (g01==1 | g02==1 | g03==1 | g04==1 | g05==1 | g06==1 | g07==1 | 
         g08==1 | g09==1 | g10==1 | g11==1 | g12==1 | g13==1 | g14==1 |
         g15==1 | g16==1 | g17==1 | g18==1 | g19==1, 1, 2), ('sim', "n\u00E3o"))
```

3º erro - Apenas retorna o erro:

_Error:
! Can't combine \`..1\` \<character\> and \`..28\` \<double\>._

Obrigado pela atenção.

**Comment by fulvionedel** [comment]
Olá @igortadeu 
Muito obrigado por informar os erros, vou tentar corrigi-los. Podes mandar o código com um exemplo em que eles acontecem?
Um abraço,

**Comment by fulvionedel** [comment]
Tentei reproduzir o 1º erro de duas formas, mas a operação funcionou pra mim:
a - apliquei a função idadeSUS sobre os dez primeiros registros do banco "aih100", do pacote; e
b - sobre as internações de residentes em Borá, SP, em janeiro de 2000, ano em que o município contava com 810 hab.

Nos dois casos a função funcionou: 
```
> table(idadeSUS(aih100[1:10,])["idade"])
idade
 0 10 27 39 46 48 61 62 78 79 
 1  1  1  1  1  1  1  1  1  1 

> aihteste <- microdatasus::fetch_datasus(2000, 1, 2000, 1, "SP", "SIH-RD") %>% 
+   filter(MUNIC_RES == "350720")
> idadeSUS(aihteste)["idade"]
  idade
1    33
2    76
3    53
4     3

# Outra forma, em um só passo:
microdatasus::fetch_datasus(2000, 1, 2000, 1, "SP", "SIH-RD") %>% 
  filter(MUNIC_RES == "350720") %>% 
  idadeSUS() %>% 
  select(idade)
```

Os outros dois erros não soube como buscar a reprodução. Se puderes mandar um exemplo com o script que produz o erro e a mensagem completa do erro, seria bom.

**Comment by igortadeu** [comment]
O 1º erro acontece quando tento fazer um cálculo agrupado por municípios. Como exemplo, baixei todas as bases de 2012 do Tocantins no DATASUS/SIHSUS. Juntei as bases e fiz o filtro o seguinte filtro:

`MUNIC_MOV == 170555`

Depois:

`descreveCSAP(csapAIH(dados_to_filtrado))`

Resultado:

```
Importados 20 registros.
Excluídos 0 (0%) registros de procedimentos obstétricos.
Excluídos NA (NA%) registros de AIH de longa permanência.
Exportados 20 (100%) registros.
Error in cut.default(idade, include.lowest = TRUE, right = FALSE, breaks = c(0:19,  : 
  'breaks' não são únicos
```

Os demais erros ocorrem após eu editar o código fonte para não executar a função idadeSUS(). Posso tentar reproduzir os erros novamente em um outro momento se você achar necessário.

Obrigado.

**Comment by fulvionedel** [comment]
Obrigado @igortadeu

Consegui reproduzir o erro e entendi o problema. Aconteceu de a idade máxima nessa seleção ser menor de 80 anos e isso gerou problemas na categorização em faixas etárias, como o limite superior de idade aparecendo duas vezes -- daí a mensagem de que os 'breaks' não são únicos. 
Ainda não sei um modo fácil de corrigir. Já arrumei esse problema (falta testar mais, talvez), mas há outros nos rótulos ("labels") das faixas etárias, ainda não sei como fazer que a função rotule corretamente as faixas etárias existentes no "data.frame".
Enquanto não se arruma isso, sugiro que apliques as funções `idadeSUS` e `csapAIH` em agrupamentos maiores que incluam os casos de interesse e depois os seleciones. Por exemplo, sobre o banco de todo o estado:

```
TO <- microdatasus::fetch_datasus(year_start = 2012, month_start = 1, year_end = 2012, month_end = 12, 
                                  uf = "TO", information_system = "SIH-RD")

Combinado <- TO %>% 
  csapAIH::csapAIH() %>% 
  filter(munint == "170555")

> Combinado %>% 
+   group_by(fxetar.det) %>% 
+   count()
# A tibble: 15 × 2
# Groups:   fxetar.det [15]
   fxetar.det     n
   <fct>      <int>
 1 "<1ano"        3
 2 " 1ano"        1
 3 " 2anos"       3
 4 " 3anos"       1
 5 " 4anos"       1
 6 " 6anos"       1
 7 " 7anos"       1
 8 " 9anos"       1
 9 "10anos"       1
10 "12anos"       2
11 "14anos"       1
12 "17anos"       1
13 "25-29"        1
14 "35-39"        1
15 "70-74"        1

> Combinado %>% 
+   group_by(fxetar5) %>% 
+   count()
# A tibble: 7 × 2
# Groups:   fxetar5 [7]
  fxetar5     n
  <fct>   <int>
1 0-4         9
2 5-9         3
3 10-14       4
4 15-19       1
5 25-29       1
6 35-39       1
7 70-74       1
```

Espero que dessa forma soluciones o problema, enquanto não vem a solução.  Obrigado novamente pela descoberta e anúncio do bug.

**Comment by igortadeu** [comment]
Muito obrigado pela resposta, @fulvionedel! Farei isso sim.

Grato.

**Comment by denis-or** [comment]
Oi @fulvionedel . Acompanhei a discussão de vocês e gostaria de fazer uma sugestão. Talvez, ao invés de usar o `max(idade, na.rm = T)` dentro do `cut`, usar o `Inf` pode ajudar de alguma forma. Reproduzi aqui no banco que o erro apareceu trocando para valores maiores que 80 e menores também. Se menor que 80 o cut coloca nas devidas classes e se maior, ele entende que é `Inf ` e cai na classe "80 +".

**Comment by fulvionedel** [comment]
Oi @denis-or 
Muitíssimo obrigado. É isso então o que se deve fazer no `cut`!! Farei isso, espero pronto ter notícias :)

**Comment by fulvionedel** [comment]
Oi @igortadeu 

Acho que arrumei, vê o teste no arquivo anexo. Instala novamente o pacote (com `remotes::install_github("fulvionedel/csapAIH")`) e testa, por favor. 
Vou fechar o "issue", mas se ainda houver algum problema, por favor reabre.

Novamente muito obrigado @denis-or 💯 
[testeidadesus.pdf](https://github.com/fulvionedel/csapAIH/files/9227729/testeidadesus.pdf)
