### ISSUE TITLE
Error installing the package csapAIH in Windows

### ISSUE THREAD

**Issue by fulvionedel** [fulvionedel/csapAIH#5]
Installation of csapAIH v0.0.3 package for Windows from sourceforge (https://sourceforge.net/projects/csapaih/), using the command `install.packages( "https://sourceforge.net/projects/csapaih/files/csapAIH-v.0.0.3.zip/download", type = "source", repos = NULL)` returns an error of "string chain with nul included", which aborts the process.

This error was noted by a colleague, and I was able to reproduce it. The proposed solution, which is to install csapAIH v0.0.3 from GitHub using devtools (`devtools::install_github("fulvionedel/csapAIH")`) worked for me, but not for her: [instalacao-pacote.pdf](https://github.com/fulvionedel/csapAIH/files/3963971/instalacao-pacote.pdf)

I still don't know what to do :B and I will work on this.

Essa discussão pode ajudar: https://github.com/ramnathv/rCharts/issues/155

**Comment by fulvionedel** [comment]
Fechei a questão com a publicação da nova versão. Veremos se o problema reaparece.

**Comment by laiovictor** [comment]
Boa tarde, quando tento instalar usando o comando,
`devtools::install_github("fulvionedel/csapAIH")`, o console retorna o seguinte erro:

```
Downloading GitHub repo fulvionedel/csapAIH@HEAD
√  checking for file 'C:\Users\laiovictor\AppData\Local\Temp\RtmpwRXUdp\remotes14646a0218cc\fulvionedel-csapAIH-f4367b1/DESCRIPTION' (809ms)
-  preparing 'csapAIH':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'csapAIH_0.0.3.2.tar.gz'
   
Installing package into ‘C:/Users/laiovictor/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'csapAIH' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/laiovictor/AppData/Local/Temp/RtmpshbYyZ/R.INSTALL2b18400563dd/csapAIH/R/csapAIH.R:229:30: '>' inesperado
228:         if (procobst.rm == TRUE) {
229:           x <- proc.obst(x) |>
                                  ^
ERROR: unable to collate and parse R files for package 'csapAIH'
* removing 'C:/Users/laiovictor/Documents/R/win-library/4.0/csapAIH'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/LAIOVI~1/AppData/Local/Temp/RtmpwRXUdp/file1464ad37aa6/csapAIH_0.0.3.2.tar.gz’ had non-zero exit status
```

Tentei baixar as pastas de diferentes versões e instalar manualmente pelo RStudio, mas quando tento chamar o pacote o seguinte erro aparece no console:
`> library(csapAIH-0.0.3.1)
Erro: unexpected numeric constant in "library(csapAIH-0.0.3"`

Poderia me ajudar?

Desde já agradeço

**Comment by denis-or** [comment]
Ei Laio. 

Desconfio ser um detalhe sobre a versão do seu R. Nesta linha, mostra que seu R está na versão 4.0, incompatível com o novo pipe ( `|>` ):
> Installing package into ‘C:/Users/laiovictor/Documents/R/win-library/**4.0**’

E, dentre o código do erro que apresentou, a linha abaixo mostra o novo pipe:
> x <- proc.obst(x) **|>**

Sugiro a atualização para a versão mais recente do R.

@fulvionedel sugiro a seguinte alteração no código nas linhas 229 e 230 do arquivo csapAIH.R:
          x <-  suppressMessages(proc.obst(x))

**Comment by laiovictor** [comment]
Obrigado Denis! Atualizei aqui e o problema foi resolvido

**Comment by laiovictor** [comment]
Olá, @fulvionedel 
Talvez por usar pacotes mais "antigos" ou que não utilizem o novo encadeamento, eu nunca tinha tido problema de compatibilidade com a versão do R ainda. Mas uma vez que descobri qual era o problema, atualizar não foi uma dificuldade, nem tem gerado qualquer transtorno até aqui. No entanto continuo tendo problemas com o uso de um vetor simples de CIDs fora do formato padronizado, não sei a que se deveria. Inclusive abri um novo tópico relatando a minha dificuldade..

**Comment by fulvionedel** [comment]
Olá @laiovictor 
Obrigado pela resposta. Vi o outro problema, é algum erro meu (ainda me atrapalho muito com o GitHub !!) espero resolver isso logo.
Abraço,
