### ISSUE TITLE
Erro na leitura de vetor com CIDs na função csapAIH() 

### ISSUE THREAD

**Issue by laiovictor** [fulvionedel/csapAIH#9]
Quando tento rodar a função csapAIH() usando um vetor de CIDs como banco de dados, recebo o seguinte erro:
 `Error in subset(banco, subset = cid < "O80" | cid >= "O85", drop = T) : 
  objeto 'banco' não encontrado`

Reproduzo aqui com o exemplo contido na documentação: 
![print erro csapaih](https://user-images.githubusercontent.com/98281330/150705291-b9b756d8-60ce-4767-853f-f0f364bf76cb.png)

Agradeço qualquer ajuda

**Comment by fulvionedel** [comment]
Olá @laiovictor, obrigado pelo aviso. Isso é um erro que devo ter incluído nesta versão, vou verificar.

**Comment by fulvionedel** [comment]
Oi @laiovictor, acho que corrigi o problema, por favor reinstala o pacote e verifica. Além disso, não deve mais precisar transformar o vetor pra fator.

**Comment by laiovictor** [comment]
Oi @fulvionedel testei aqui e deu certo! Muito obrigado

**Comment by fulvionedel** [comment]
Ótimo, então vou fechar essa questão. 
Fico feliz que o pacote seja útil :)
